// app/layout.js
import "./globals.css";
import Navbar from "./components/navbar";

export const metadata = {
  title: "Eventos",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
