// app/layout.js
import EventProvider from "./context/EventContext";
import { LoginProvider } from "./context/LoginContext";
import "./globals.css";

export const metadata = {
  title: "Eventos",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <LoginProvider>
        <EventProvider>
          {children} 
        </EventProvider>
      </LoginProvider>
      </body>
    </html>
  );
}
 
