// app/layout.js
import EventProvider from "./context/EventContext";
import "./globals.css";

export const metadata = {
  title: "Eventos",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body>
      <EventProvider>
        {children} 
      </EventProvider>
      </body>
    </html>
  );
}

